acme_store_homepage:
    pattern:  /store/{name}
    defaults: { _controller: AcmeStoreBundle:Default:index }
    
acme_store_create:
    pattern:  /createStore/{name}
    defaults: { _controller: AcmeStoreBundle:Default:create } 
    
acme_store_show:
    pattern:  /showStore/{id}
    defaults: { _controller: AcmeStoreBundle:Default:show }       